Delete redundant tailwind css import
frozar/scolaire-front pull request #160
Opened 2023-07-03 12:06 UTC by Quentin0312

2023-07-03 12:26 UTC, Lucas-dev-974 approved these changes

2023-07-04 09:08 UTC, frozar requested changes

2023-07-04 09:08 UTC, frozar commented on src/css/index.css
> +#ramassages-board > header > #filters > .left {
Saut de ligne au dessus de chacun règle CSS

2023-07-05 11:00 UTC, frozar approved these changes

2023-07-05 11:04 UTC, merged