Redesign
frozar/scolaire-front pull request #45
Opened 2023-05-10 10:43 UTC by Lucas-dev-974

2023-05-10 13:35 UTC, frozar requested changes

2023-05-10 13:35 UTC, frozar commented on src/StateGui.tsx
> +  onWindow: string;
`onWindow` -> `selectedMenu`

2023-05-10 13:35 UTC, frozar commented on src/StateGui.tsx
> +  function setOnWindow(window: string) {
`setOnWindow` -> `setSelectedMenu`

2023-05-10 13:35 UTC, frozar commented on src/StateGui.tsx
> +
Ajouter un getter `getSelectedMenu`.

2023-05-10 13:35 UTC, frozar commented on src/App.tsx
> +          <Match when={stateGui.onWindow == "graphicage"}>
Utiliser le getter `setSelectedMenu` : on ne doit pas accèder directement au champ du state.

2023-05-10 13:35 UTC, frozar commented on src/layout/NavLateral.tsx
> +  const MenuOnClick = () => {
`MenuOnClick` -> `onClickHandler`

2023-05-10 13:35 UTC, frozar commented on src/layout/NavLateral.tsx
> +    <li id={"window_" + url} class="lateral-nav-item" onclick={MenuOnClick}>
`onclick` -> `onClick`

2023-05-10 13:35 UTC, frozar commented on src/layout/NavLateral.tsx
> +    <li id={"window_" + url} class="lateral-nav-item" onclick={MenuOnClick}>
Supprimer l'attribut `id`.

2023-05-10 13:35 UTC, frozar commented on src/layout/NavLateral.tsx
> +    <li id={"window_" + url} class="lateral-nav-item" onclick={MenuOnClick}>
Utiliser l'attribut `classList` et le getter `getSelectedMenu()` comme le montre [ce tuto](https://www.solidjs.com/tutorial/bindings_classlist?solved). Ca te supprimera le block que tu as mis avec `document.addEventListener`. C'est ce type d'exemple qui me fait dire qu'il te manque des bases en solidjs. Il faut bien comprendre que je considère l'intégralité du tutorial officiel comme étant les bases de solidjs.

Et au passage, ce que tu as fait avec le `document.addEventListener("DOMContentLoaded",...`, en solidjs c'est le handler `onMount` qui fait ce travail.

2023-05-10 13:35 UTC, frozar commented on src/layout/NavTop.tsx
> +      <nav class="w-full bg-[#062F3F] text-white h-[60px] flex  justify-end items-center pr-5">
La valeur `#062F3F`, c'est mieux s'il y a une classe dédiée dans le css qui reprendre cette valeur. D'ailleurs, il faudrait que plutôt faire une classe CSS pour la `nav` avec toutes les classes qui vont bien grâce à `@apply`.

2023-05-10 13:35 UTC, frozar commented on src/pages/Arret.tsx
> +export default function PageArrets() {
Après un `export default`, on ne met pas de nom à la fonction -> ~PageArrets~

2023-05-10 13:35 UTC, frozar commented on src/pages/Arret.tsx
> +export default function PageArrets() {
C'est partout pareil pour toutes les fichiers qui sont dans le dossier `pages`.

2023-05-10 13:35 UTC, frozar commented on src/pages/Arret.tsx
> +export default function PageArrets() {
Le nom de dossier `pages` est malheureux : ce ne sont pas des pages, il n'y aura que peu de comminucation avec le server quand on clique sur un menu lorsqu'on utilisera l'application.
=> Renommer `pages` -> `views`.

2023-05-11 05:34 UTC, Lucas-dev-974 commented on src/layout/NavLateral.tsx
> +    <li id={"window_" + url} class="lateral-nav-item" onclick={MenuOnClick}>
ça prenait pas avec le onMount j'avais essayer mais le onMount s’exécuter avant que l'élément li ne sois disponible j'obtenait un undefined quand j'essayais de récupérer le composant via son id

2023-05-11 10:25 UTC, frozar approved these changes

2023-05-11 10:25 UTC, merged