Add arrows to routes
frozar/scolaire-front pull request #80
Opened 2023-05-25 12:27 UTC by Quentin0312

2023-05-25 13:03 UTC, Richard908 commented on src/line/BusLines.tsx
> +
Ajouter le createEffect pour le changement de couleur

2023-05-30 05:03 UTC, frozar requested changes

2023-05-30 05:03 UTC, frozar commented on src/line/BusLines.tsx
>    createEffect(() => {
Sauter une ligne.

2023-06-05 12:47 UTC, frozar approved these changes

2023-06-05 12:47 UTC, merged